# Generated by Django 5.1.13 on 2025-11-18 22:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0009_add_test_origin_start_time_platform_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingBuild",
            fields=[
                ("build_id", models.TextField(primary_key=True, serialize=False)),
                ("checkout_id", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pass"), ("F", "Fail"), ("I", "Incomplete")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "db_table": "pending_build",
            },
        ),
        migrations.CreateModel(
            name="PendingTest",
            fields=[
                ("test_id", models.TextField(primary_key=True, serialize=False)),
                ("origin", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=100)),
                (
                    "compatible",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("build_id", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pass"), ("F", "Fail"), ("I", "Incomplete")],
                        max_length=1,
                    ),
                ),
                ("is_boot", models.BooleanField()),
            ],
            options={
                "db_table": "pending_test",
            },
        ),
        migrations.CreateModel(
            name="HardwareStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_id", models.TextField()),
                ("origin", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=100)),
                (
                    "compatibles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("build_pass", models.IntegerField(default=0)),
                ("build_failed", models.IntegerField(default=0)),
                ("build_inc", models.IntegerField(default=0)),
                ("boot_pass", models.IntegerField(default=0)),
                ("boot_failed", models.IntegerField(default=0)),
                ("boot_inc", models.IntegerField(default=0)),
                ("test_pass", models.IntegerField(default=0)),
                ("test_failed", models.IntegerField(default=0)),
                ("test_inc", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "hardware_status",
                "indexes": [
                    models.Index(
                        fields=["origin", "start_time"], name="hw_status_origin_time"
                    ),
                    models.Index(fields=["checkout_id"], name="hw_status_checkout_id"),
                ],
                "unique_together": {("origin", "platform", "checkout_id")},
            },
        ),
        migrations.CreateModel(
            name="LatestCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_id", models.TextField()),
                ("origin", models.CharField(max_length=100)),
                ("tree_name", models.TextField()),
                ("git_repository_url", models.TextField()),
                ("git_repository_branch", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
            ],
            options={
                "db_table": "latest_checkout",
                "indexes": [
                    models.Index(fields=["checkout_id"], name="lc_checkout_id")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "origin",
                            "tree_name",
                            "git_repository_url",
                            "git_repository_branch",
                        ),
                        name="latest_checkout_unique",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
