# Generated by Django 5.1.13 on 2025-11-03 18:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kernelCI_app", "0009_add_test_origin_start_time_platform_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="BootsStatus",
            fields=[
                ("build_id", models.TextField(primary_key=True, serialize=False)),
                ("pass_count", models.IntegerField(db_column="pass", default=0)),
                ("failed", models.IntegerField(default=0)),
                ("inc", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "boots_status",
            },
        ),
        migrations.CreateModel(
            name="NewBoot",
            fields=[
                ("boot_id", models.TextField(primary_key=True, serialize=False)),
                ("build_id", models.TextField()),
                ("boot_origin", models.CharField(max_length=100)),
                ("boot_platform", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("SKIP", "Skip"),
                            ("ERROR", "Error"),
                            ("MISS", "Miss"),
                            ("DONE", "Done"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "new_boot",
            },
        ),
        migrations.CreateModel(
            name="NewBuild",
            fields=[
                ("build_id", models.TextField(primary_key=True, serialize=False)),
                ("checkout_id", models.TextField()),
                ("build_origin", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("SKIP", "Skip"),
                            ("ERROR", "Error"),
                            ("MISS", "Miss"),
                            ("DONE", "Done"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "new_build",
            },
        ),
        migrations.CreateModel(
            name="NewTest",
            fields=[
                ("test_id", models.TextField(primary_key=True, serialize=False)),
                ("build_id", models.TextField()),
                ("test_origin", models.CharField(max_length=100)),
                ("test_platform", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("SKIP", "Skip"),
                            ("ERROR", "Error"),
                            ("MISS", "Miss"),
                            ("DONE", "Done"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "new_test",
            },
        ),
        migrations.CreateModel(
            name="TestsStatus",
            fields=[
                ("build_id", models.TextField(primary_key=True, serialize=False)),
                ("pass_count", models.IntegerField(db_column="pass", default=0)),
                ("failed", models.IntegerField(default=0)),
                ("inc", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "tests_status",
            },
        ),
        migrations.CreateModel(
            name="BuildStatusByHardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hardware_origin", models.CharField(max_length=100)),
                ("hardware_platform", models.CharField(max_length=100)),
                ("build_id", models.TextField()),
            ],
            options={
                "db_table": "build_status_by_hardware",
                "unique_together": {
                    ("hardware_origin", "hardware_platform", "build_id")
                },
            },
        ),
        migrations.CreateModel(
            name="HardwareStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hardware_origin", models.CharField(max_length=100)),
                ("hardware_platform", models.CharField(max_length=100)),
                (
                    "compatibles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("checkout_id", models.TextField()),
                ("date", models.DateTimeField()),
                ("build_pass", models.IntegerField()),
                ("build_failed", models.IntegerField()),
                ("build_inc", models.IntegerField()),
                ("boot_pass", models.IntegerField()),
                ("boot_failed", models.IntegerField()),
                ("boot_inc", models.IntegerField()),
                ("test_pass", models.IntegerField()),
                ("test_failed", models.IntegerField()),
                ("test_inc", models.IntegerField()),
            ],
            options={
                "db_table": "hardware_status",
                "unique_together": {("hardware_origin", "hardware_platform", "date")},
            },
        ),
    ]
